export const RAKUTEN_CATALOG_COLUMNS = [
  'productId',
  'productName',
  'skuNumber',
  'primaryCategory',
  'secondaryCategory',
  'productUrl',
  'productImageUrl',
  'buyUrl',
  'shortProductDescription',
  'longProductDescription',
  'discount',
  'discountType',
  'salePrice',
  'retailPrice',
  'beginDate',
  'endDate',
  'brand',
  'shipping',
  'keywords',
  'manufacturerPart',
  'manufacturerName',
  'shippingInformation',
  'availability',
  'universalProductCode',
  'classId',
  'currency',
  'm1',
  'pixel',
];

// todo 이건 나중에 DB로 옮기자
export const ADVERTISERS = [
  { name: '블루밍데일즈', mid: 13867, deliveryToKorea: true, shopCode: 'A024' },
  { name: '메이시스', mid: 37978, deliveryToKorea: true, shopCode: 'A025' },
  // { name: '매치스패션', mid: 39265, deliveryToKorea: true, shopCode: 'A006' },
  // { name: '스플렌디드', mid: 42623, deliveryToKorea: true, shopCode: 'A035' },
  // { name: '앤 테일러', mid: 43432, deliveryToKorea: true, shopCode: 'B003' },
  // { name: '샵밥', mid: 43802, deliveryToKorea: true, shopCode: 'A017' },
  // { name: '이스트데인', mid: 43804, deliveryToKorea: true, shopCode: 'A027' },
  // { name: '더 더블 에프', mid: 44328, deliveryToKorea: true, shopCode: 'A033' },
  // { name: '하비니콜스', mid: 44787, deliveryToKorea: true, shopCode: 'A011' },
  // { name: '칼토티 부티크', mid: 45516, deliveryToKorea: true, shopCode: 'A044' },
  // { name: '유케이사커샵', mid: 46108, deliveryToKorea: true, shopCode: 'A036' },
];
